### get all users
GET http://localhost:3000/api/users

### get all towns
GET http://localhost:3000/api/users/town

### get all drivers
GET http://localhost:3000/api/users/drivers

### get Single user
GET http://localhost:3000/api/users/delete/3

### del Single user
DELETE http://localhost:3000/api/users/1

### Create user
POST http://localhost:3000/api/users
Content-Type:  application/json

{
  "name": "Mike",
  "town": "Kazkur",
  "isDriver": false
}

### Edit user
PUT http://localhost:3000/api/users/baa7692a-5f92-4d42-bee9-6d0753fb12c1
Content-Type:  application/json

{
  "name": "UpdatedName",
  "town": "UpdatedTown",
  "isDriver": true
}