GET http://localhost:3000

### get all users
GET http://localhost:3000/api/users

### get all towns
GET http://localhost:3000/api/users/town

### get all drivers
GET http://localhost:3000/api/users/drivers

### get Single user
GET http://localhost:3000/api/users/delete/3

### del Single user
DELETE http://localhost:3000/api/users/1

### Create user
POST http://localhost:3000/api/users
Content-Type:  application/json

{
  "name": "Mike",
  "town": "Kazkur",
  "isDriver": false
}